name: CMake

on:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/cmake.yml'
    - '**CMakeLists.txt'
    - '**.cmake'
    - '**test_*'
  pull_request:
    paths:
    - '.github/workflows/cmake.yml'
    - '**CMakeLists.txt'
    - '**.cmake'
    - '**test_*'

env:
  CXXFLAGS: "-Wall -pedantic"
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  tlapack_DIR: ${{github.workspace}}/tlapack
  Catch2_DIR: ${{github.workspace}}/Catch2

defaults:
  run:
    shell: bash

jobs:

  test-tlapack-templates:
    # Use GNU compilers
  
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout testBLAS
      uses: actions/checkout@v2

    - name: Install MPFR C++
      run: sudo apt install libmpfrc++-dev

    - name: Checkout Catch2
      uses: actions/checkout@v2
      with:
        repository: catchorg/Catch2
        path: Catch2

    - name: Checkout <T>LAPACK
      uses: actions/checkout@v2
      with:
        repository: tlapack/tlapack
        path: tlapack

    - name: Build and install <T>LAPACK
      working-directory: ${{env.tlapack_DIR}}
      run: |
        mkdir build
        cmake -Bbuild -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=${{env.tlapack_DIR}}
        cmake --build build --target install

    - name: Configure testBLAS
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B build
        -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -D TEST_MPFR=ON
        -D Catch2_DIR=${{env.Catch2_DIR}}
        -D tlapack_DIR=${{env.tlapack_DIR}}

    - name: Build testBLAS
      # Build your program with the given configuration
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      continue-on-error: true
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ${{github.workspace}}/build/tester

  test-blaspp-wrappers:
    runs-on: ubuntu-latest
    env:
      blaspp_DIR: ${{github.workspace}}/blaspp
    
    steps:
    
    - name: Checkout testBLAS
      uses: actions/checkout@v2

    - name: Checkout Catch2
      uses: actions/checkout@v2
      with:
        repository: catchorg/Catch2
        path: Catch2

    - name: Install Reference BLAS
      run: sudo apt install libblas-dev

    - name: Checkout BLAS++
      run: git clone https://bitbucket.org/weslleyspereira/blaspp ${{env.blaspp_DIR}}

    - name: Build and install BLAS++
      working-directory: ${{env.blaspp_DIR}}
      run: |
        git checkout tlapack
        mkdir build
        cmake -Bbuild -Dbuild_tests=OFF -DCMAKE_INSTALL_PREFIX=${{env.blaspp_DIR}}
        cmake --build build --target install

    - name: Checkout <T>LAPACK
      uses: actions/checkout@v2
      with:
        repository: tlapack/tlapack
        path: tlapack

    - name: Build and install <T>LAPACK
      working-directory: ${{env.tlapack_DIR}}
      run: |
        mkdir build
        cmake -Bbuild -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DUSE_BLASPP_WRAPPERS=ON -Dblaspp_DIR=${{env.blaspp_DIR}} -DCMAKE_INSTALL_PREFIX=${{env.tlapack_DIR}}
        cmake --build build --target install

    - name: Configure testBLAS
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B build
        -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -D Catch2_DIR=${{env.Catch2_DIR}}
        -D tlapack_DIR=${{env.tlapack_DIR}}

    - name: Build testBLAS
      # Build your program with the given configuration
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    # Mind that the job won't fail if only this step fails
    - name: Test INF and NAN propagation in iamax
      working-directory: ${{github.workspace}}/build
      continue-on-error: true
      run: |
        echo "Mind that the job won't fail because of this step."
        ./tester -# [#test_infNaN_iamax] -r compact

    # Mind that the job won't fail if only this step fails
    - name: Test INF and NAN propagation in nrm2
      working-directory: ${{github.workspace}}/build
      continue-on-error: true
      run: |
        echo "Mind that the job won't fail because of this step."
        ./tester -# [#test_infNaN_nrm2] -r compact

    # Mind that the job won't fail if only this step fails
    - name: Test Corner Cases
      working-directory: ${{github.workspace}}/build
      continue-on-error: true
      run: |
        echo "Mind that the job won't fail because of this step."
        ./tester -# [#test_corner_cases] -r compact